import { BsMarkdown } from "react-icons/bs";
import {
  PiFileCss,
  PiFileCsv,
  PiFileDoc,
  PiFileHtml,
  PiFileJpg,
  PiFileJs,
  PiFile,
  PiFilePng,
  PiFilePpt,
  PiFileSql,
  PiFileSvg,
  PiFileText,
  PiFileTs,
  PiFileVideo,
  PiFilePdf,
  PiFileImage,
  PiFileXls,
  PiFileZip,
  PiFileAudio,
  PiFileArchive,
  PiNotebook,
} from "react-icons/pi";

export const fileTypeIcons: any = {
  default: PiFile,
  pdf: PiFilePdf,
  csv: PiFileCsv,
  txt: PiFileText,
  html: PiFileHtml,
  css: PiFileCss,
  js: PiFileJs,
  ts: PiFileTs,
  jpg: PiFileJpg,
  png: PiFilePng,
  svg: PiFileSvg,
  jpeg: PiFileImage,
  webp: PiFileImage,
  mp3: PiFileAudio,
  mp4: PiFileVideo,
  gif: PiFileVideo,
  avi: PiFileVideo,
  mov: PiFileVideo,
  mkv: PiFileVideo,
  flv: PiFileVideo,
  doc: PiFileDoc,
  docx: PiFileDoc,
  ppt: PiFilePpt,
  pptx: PiFilePpt,
  xls: PiFileXls,
  xlsx: PiFileXls,
  sql: PiFileSql,
  zip: PiFileZip,
  rar: PiFileArchive,
  "7z": PiFileArchive,
  tar: PiFileArchive,
  gz: PiFileArchive,
  "tar.gz": PiFileArchive,
  md: BsMarkdown,
  epub: PiNotebook,
  mobi: PiNotebook,
};
